####################
# DEV ENVIRONMENT! #
####################
services:
  marimo:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: marimo-docker:dev
    ports:
      - "127.0.0.1:2718:2718"
    restart: unless-stopped
    volumes:
      - ./dev_notebooks:/home/app_user/notebooks
      - ./utils:/home/app_user/notebooks/utils
      - ./.marimo.toml:/home/app_user/.marimo.toml
    environment:
      FLASHPOINT_API_KEY: ${FLASHPOINT_API_KEY}
      IPQS_API_KEY: ${IPQS_API_KEY}
      MARIMO_HOST: ${MARIMO_HOST}
      MARIMO_PORT: ${MARIMO_PORT}
      MARIMO_TOKEN_PASSWORD: ${MARIMO_TOKEN_PASSWORD}
      SLYCOOPER_MONGO_URI: ${SLYCOOPER_MONGO_URI}
      SLYCOOPER_MYSQL_URI: ${SLYCOOPER_MYSQL_URI}
      CACHEMEOUSSIDE_API_URL: ${CACHEMEOUSSIDE_API_URL}
      SPYCLOUD_API_ATO_KEY: ${SPYCLOUD_API_ATO_KEY}
      SPYCLOUD_API_INV_KEY: ${SPYCLOUD_API_INV_KEY}
      SPYCLOUD_API_SIP_KEY: ${SPYCLOUD_API_SIP_KEY}
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_API_SID: ${TWILIO_API_SID}
      TWILIO_API_SECRET: ${TWILIO_API_SECRET}
      URLSCAN_API_KEY: ${URLSCAN_API_KEY}
    command: bash -c 'source /home/app_user/venv/bin/activate && marimo edit --headless --token --token-password ${MARIMO_TOKEN_PASSWORD} -p ${MARIMO_PORT} --host ${MARIMO_HOST}'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:2718/health" ]
      interval: 30s
      timeout: 3s
      retries: 3
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # <-- Mount config file
    extra_hosts:
      - "host.docker.internal:host-gateway"
