services:
  marimo:
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: build
    networks:
      - lab
    ports:
      - "100.94.216.28:2718:2718"
    restart: unless-stopped
    volumes:
      - /opt/docker/marimo/marimo_notebooks:/home/app_user/notebooks
      - /opt/docker/marimo/.marimo.toml:/home/app_user/.marimo.toml
    environment:
      MARIMO_HOST: ${MARIMO_HOST}
      MARIMO_PORT: ${MARIMO_PORT}
      MARIMO_TOKEN_PASSWORD: ${MARIMO_TOKEN_PASSWORD}
    command: bash -c 'source /home/app_user/venv/bin/activate && marimo edit --headless --token --token-password ${MARIMO_TOKEN_PASSWORD} -p ${MARIMO_PORT} --host ${MARIMO_HOST}'
    healthcheck:
      test: [ "CMD", "curl", "-f", "https://marimo.trashcollector.dev/health" ]
      interval: 30s
      timeout: 3s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wikijs.rule=Host(`marimo.trashcollector.dev`)"
      - "traefik.http.routers.wikijs.entrypoints=https"
      - "traefik.http.routers.wikijs.tls.certresolver=letsencrypt"

networks:
  lab:
    external: true

