services:
  marimo:
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: build
    networks:
      - lab
    ports:
      - "127.0.0.1:2718:2718"
      - "100.94.216.28:2718:2718"
    restart: unless-stopped
    volumes:
      - /opt/docker/marimo/marimo_notebooks:/home/app_user/notebooks
      - /opt/docker/marimo/.marimo.toml:/home/app_user/.marimo.toml
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      FLASHPOINT_API_KEY: ${FLASHPOINT_API_KEY}
      MARIMO_HOST: ${MARIMO_HOST}
      MARIMO_PORT: ${MARIMO_PORT}
      MARIMO_TOKEN_PASSWORD: ${MARIMO_TOKEN_PASSWORD}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_IPQS_CACHE_COLL: ${MONGO_IPQS_CACHE_COLL}
      IPQS_API_KEY: ${IPQS_API_KEY}
      SHOUTRRR_URL: ${SHOUTRRR_URL}
      SHOUTRRR_API_KEY: ${SHOUTRRR_API_KEY}
      SHOUTRRR_ALERTING_CHANNEL: ${SHOUTRRR_ALERTING_CHANNEL}
      SHOUTRRR_RESULTS_CHANNEL: ${SHOUTRRR_RESULTS_CHANNEL}
      SLYCOOPER_MONGO_URI: ${SLYCOOPER_MONGO_URI}
      SLYCOOPER_MYSQL_URI: ${SLYCOOPER_MYSQL_URI}
      SPYCLOUD_API_ATO_KEY: ${SPYCLOUD_API_ATO_KEY}
      SPYCLOUD_API_INV_KEY: ${SPYCLOUD_API_INV_KEY}
      SPYCLOUD_API_SIP_KEY: ${SPYCLOUD_API_SIP_KEY}
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_API_SID: ${TWILIO_API_SID}
      TWILIO_API_SECRET: ${TWILIO_API_SECRET}
      URLSCAN_API_KEY: ${URLSCAN_API_KEY}
    command: bash -c 'source /home/app_user/venv/bin/activate && marimo edit --headless --token --token-password ${MARIMO_TOKEN_PASSWORD} -p ${MARIMO_PORT} --host ${MARIMO_HOST}'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:2718/health" ]
      interval: 30s
      timeout: 3s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.marimo.rule=Host(`marimo.trashcollector.dev`)"
      - "traefik.http.routers.marimo.entrypoints=https"
      - "traefik.http.routers.marimo.tls.certresolver=letsencrypt"

networks:
  lab:
    external: true
